development:
  adapter: postgresql
  encoding: unicode
  database: makersbnb_test
  pool: 2
  #username: appscat
  #password: your_password

production:
  adapter: postgresql
  encoding: unicode
  database: makersbnb
  pool: 2
  #username: appscat
  #password: your_password